version: "3.8"

services:
  rasa:
    image: rasa/rasa:3.6.2
    volumes:
      - ./rasa:/app
    ports:
      - "5005:5005"
    command: >
      run --enable-api --cors "*" --debug
    depends_on:
      - action_server

  action_server:
    build: ./rasa/actions
    ports:
      - "5055:5055"
