version: "3.9"

services:
  rasa:
    image: rasa/rasa:3.6.2
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
      - ./rasa/models:/app/models
    command: run --enable-api --cors "*"
    depends_on:
      - rasa_actions
    networks:
      - probaho_network

  rasa_actions:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    networks:
      - probaho_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rasa
    networks:
      - probaho_network

networks:
  probaho_network:
    driver: bridge
