version: '3.9'

services:
  rasa:
    image: rasa/rasa:3.6.2
    container_name: rasa
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command: >
      rasa run --enable-api --cors "*" --debug --port 5005
    depends_on:
      - rasa_actions

  rasa_actions:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile
    container_name: actions
    ports:
      - "5055:5055"
    volumes:
      - ./rasa/actions:/app/actions
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - rasa