recipe: default.v1
assistant_id: ewu_chatbot
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.25

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50
  - name: TEDPolicy
    max_history: 5
    epochs: 80
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.4   # triggers fallback if confidence < 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

#taken from https://github.com/Atkiya/rasabot